-- MySQL Script generated by MySQL Workbench
-- Tue Dec 12 19:16:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema peliculasUsuarios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema peliculasUsuarios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `peliculasUsuarios` DEFAULT CHARACTER SET utf8 ;
USE `peliculasUsuarios` ;

-- -----------------------------------------------------
-- Table `peliculasUsuarios`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculasUsuarios`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `enable` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peliculasUsuarios`.`Criticas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculasUsuarios`.`Criticas` (
  `idCritica` INT NOT NULL AUTO_INCREMENT,
  `idPelicula` INT NOT NULL,
  `valoracion` VARCHAR(500) NOT NULL,
  `nota` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idCritica`),
  INDEX `fk_Criticas_Usuarios_idx` (`Usuarios_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Criticas_Usuarios`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `peliculasUsuarios`.`Usuarios` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peliculasUsuarios`.`Authorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculasUsuarios`.`Authorities` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `authority` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peliculasUsuarios`.`Usuarios_tiene_Authorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculasUsuarios`.`Usuarios_tiene_Authorities` (
  `Usuarios_idUsuario` INT NOT NULL,
  `Authorities_idRol` INT NOT NULL,
  PRIMARY KEY (`Usuarios_idUsuario`, `Authorities_idRol`),
  INDEX `fk_Usuarios_tiene_Authorities_Authorities1_idx` (`Authorities_idRol` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_tiene_Authorities_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `peliculasUsuarios`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_tiene_Authorities_Authorities1`
    FOREIGN KEY (`Authorities_idRol`)
    REFERENCES `peliculasUsuarios`.`Authorities` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
