-- MySQL Script generated by MySQL Workbench
-- Mon Nov  6 19:26:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema peliculasdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema peliculasdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `peliculasdb` DEFAULT CHARACTER SET utf8 ;
USE `peliculasdb` ;

-- -----------------------------------------------------
-- Table `peliculasdb`.`pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculasdb`.`pelicula` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `anno` INT NOT NULL,
  `duracion` INT NOT NULL,
  `pais` VARCHAR(255) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `genero` VARCHAR(255) NOT NULL,
  `sinopsis` VARCHAR(500) NOT NULL,
  `portada` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));

ALTER TABLE pelicula auto_increment = 1;

-- -----------------------------------------------------
-- Table `peliculasdb`.`actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculasdb`.`actor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `pais` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));

ALTER TABLE actor auto_increment = 1;

-- -----------------------------------------------------
-- Table `peliculasdb`.`peliculasActores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peliculasdb`.`peliculasActores` (
  `pelicula_id` INT NOT NULL,
  `actor_id` INT NOT NULL,
  PRIMARY KEY (`pelicula_id`, `actor_id`),
  INDEX `fk_peliculasActores_pelicula_idx` (`pelicula_id` ASC) VISIBLE,
  INDEX `fk_peliculasActores_actor1_idx` (`actor_id` ASC) VISIBLE,
  CONSTRAINT `fk_peliculasActores_pelicula`
    FOREIGN KEY (`pelicula_id`)
    REFERENCES `peliculasdb`.`pelicula` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peliculasActores_actor1`
    FOREIGN KEY (`actor_id`)
    REFERENCES `peliculasdb`.`actor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



